arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false
output-dir: lib/l10n
output-class: AppLocalizations
nullable-getter: false
untranslated-messages-file: untranslated_messages.txt
